development: &development
  adapter: mysql2
  host: localhost
  database: codemasters_development
  username: root
  password:
  socket: /tmp/mysql.sock

test: &test
  adapter: mysql2
  host: localhost
  database: codemasters_test
  username: root
  password:
  socket: /tmp/mysql.sock

cucumber:
  <<: *test